from typing import Any

config: Any

def begin_transaction() -> Any: ...
def configure(*_args: Any, **_kwargs: Any) -> None: ...
def get_context() -> Any: ...
def is_offline_mode() -> bool: ...
def run_migrations(**_kwargs: Any) -> None: ...
